
package br.com.caelum.estoque.cliente;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EstoqueWS", targetNamespace = "http://ws.estoque.caelum.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EstoqueWS {


    /**
     * 
     * @return
     *     returns br.com.caelum.estoque.cliente.ListaItens
     */
    @WebMethod(action = "http://ws.estoque.caelum.com.br/EstoqueWS/todosOsItensRequest")
    @WebResult(name = "itens", targetNamespace = "")
    @RequestWrapper(localName = "todosOsItens", targetNamespace = "http://ws.estoque.caelum.com.br/", className = "br.com.caelum.estoque.cliente.TodosOsItens")
    @ResponseWrapper(localName = "todosOsItensResponse", targetNamespace = "http://ws.estoque.caelum.com.br/", className = "br.com.caelum.estoque.cliente.TodosOsItensResponse")
    @Action(input = "http://ws.estoque.caelum.com.br/EstoqueWS/todosOsItensRequest", output = "http://ws.estoque.caelum.com.br/EstoqueWS/todosOsItensResponse")
    public ListaItens todosOsItens();

    /**
     * 
     * @param parameters
     * @param token
     * @return
     *     returns br.com.caelum.estoque.cliente.CadastrarItemResponse
     * @throws AutorizacaoException
     */
    @WebMethod(operationName = "CadastrarItem", action = "http://ws.estoque.caelum.com.br/EstoqueWS/CadastrarItemRequest")
    @WebResult(name = "CadastrarItemResponse", targetNamespace = "http://ws.estoque.caelum.com.br/", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://ws.estoque.caelum.com.br/EstoqueWS/CadastrarItemRequest", output = "http://ws.estoque.caelum.com.br/EstoqueWS/CadastrarItemResponse", fault = {
        @FaultAction(className = AutorizacaoException.class, value = "http://ws.estoque.caelum.com.br/EstoqueWS/CadastrarItem/Fault/AutorizacaoException")
    })
    public CadastrarItemResponse cadastrarItem(
        @WebParam(name = "CadastrarItem", targetNamespace = "http://ws.estoque.caelum.com.br/", partName = "parameters")
        CadastrarItem parameters,
        @WebParam(name = "token", targetNamespace = "http://ws.estoque.caelum.com.br/", header = true, partName = "token")
        TokenUsuario token)
        throws AutorizacaoException
    ;

    /**
     * 
     * @param filtros
     * @return
     *     returns br.com.caelum.estoque.cliente.ListaItens
     */
    @WebMethod(action = "http://ws.estoque.caelum.com.br/EstoqueWS/todosOsItens2Request")
    @WebResult(name = "itens2", targetNamespace = "")
    @RequestWrapper(localName = "todosOsItens2", targetNamespace = "http://ws.estoque.caelum.com.br/", className = "br.com.caelum.estoque.cliente.TodosOsItens2")
    @ResponseWrapper(localName = "todosOsItens2Response", targetNamespace = "http://ws.estoque.caelum.com.br/", className = "br.com.caelum.estoque.cliente.TodosOsItens2Response")
    @Action(input = "http://ws.estoque.caelum.com.br/EstoqueWS/todosOsItens2Request", output = "http://ws.estoque.caelum.com.br/EstoqueWS/todosOsItens2Response")
    public ListaItens todosOsItens2(
        @WebParam(name = "filtros", targetNamespace = "")
        Filtros filtros);

    /**
     * 
     * @return
     *     returns java.util.List<br.com.caelum.estoque.cliente.Item>
     */
    @WebMethod(action = "http://ws.estoque.caelum.com.br/EstoqueWS/todosOsItens3Request")
    @WebResult(name = "itens", targetNamespace = "")
    @RequestWrapper(localName = "todosOsItens3", targetNamespace = "http://ws.estoque.caelum.com.br/", className = "br.com.caelum.estoque.cliente.TodosOsItens3")
    @ResponseWrapper(localName = "itens", targetNamespace = "http://ws.estoque.caelum.com.br/", className = "br.com.caelum.estoque.cliente.Itens")
    @Action(input = "http://ws.estoque.caelum.com.br/EstoqueWS/todosOsItens3Request", output = "http://ws.estoque.caelum.com.br/EstoqueWS/todosOsItens3Response")
    public List<Item> todosOsItens3();

}
